name: Build Ticker Info

on:
  workflow_dispatch:
  schedule:
    - cron: "45 19 * * 1-5"  # 3:45 PM EST (07:45 UTC) Monday through Friday

jobs:
  build-ticker-info:
    strategy:
      fail-fast: false
      matrix:
        part_index: [0, 1, 2, 3]  # Four partitions for Phase 1
        part_total: [4]
    runs-on: ubuntu-latest
    timeout-minutes: 180  # Allow up to 180 minutes for safety

    steps:
      - name: Print workflow start time (EDT)
        run: |
          echo "Workflow started at $(date -u -d '4 hours ago' +'%I:%M %p EDT on %A, %B %d, %Y')"
      
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yahooquery pandas requests tqdm

      - name: Run ticker info builder (partition ${{ matrix.part_index }}, Phase 1)
        run: |
          python scripts/build_ticker_info.py \
            --part-index ${{ matrix.part_index }} \
            --part-total ${{ matrix.part_total }} \
            --verbose
        working-directory: .

      - name: Upload partition artifact
        uses: actions/upload-artifact@v4
        with:
          name: ticker-info-part-${{ matrix.part_index }}
          path: |
            data/ticker_info_part_${{ matrix.part_index }}.json
            data/partition_summary.json
            data/unresolved_tickers.txt
            logs/build_ticker_info.log
          retention-days: 5

      - name: Print workflow end time (EDT)
        run: |
          echo "Workflow ended at $(date -u -d '4 hours ago' +'%I:%M %p EDT on %A, %B %d, %Y')"

  merge-ticker-info:
    needs: build-ticker-info
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Print workflow start time (EDT)
        run: |
          echo "Workflow started at $(date -u -d '4 hours ago' +'%I:%M %p EDT on %A, %B %d, %Y')"

      - uses: actions/checkout@v4

      - name: Download partition artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: ticker-info-part-*
          merge-multiple: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yahooquery pandas requests tqdm

      - name: Prepare files for merge
        run: |
          mkdir -p data logs
          find artifacts -type f -name "ticker_info_part_*.json" -exec cp {} data/ \; || true
          find artifacts -type f -name "partition_summary.json" -exec cp {} data/ \; || true
          find artifacts -type f -name "unresolved_tickers.txt" -exec cp {} data/ \; || true
          ls -l data/ | grep -E "ticker_info_part_|partition_summary.json|unresolved_tickers.txt" || echo "No expected files copied"

      - name: Merge ticker_info.json files
        run: |
          python scripts/merge_ticker_info.py data
        working-directory: .

      - name: Commit merged ticker_info.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git stash push --include-untracked
          git pull --rebase origin main
          git stash pop || echo "No stash to pop"
          git add data/ticker_info.json data/partition_summary.json data/unresolved_tickers.txt
          edt_time=$(date -u -d "4 hours ago" +"%I:%M %p EDT on %A, %B %d, %Y")
          git commit -m "Commit merged ticker_info.json, partition_summary.json, unresolved_tickers.txt [${edt_time}]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git || echo "Push failed, possibly no changes"

      - name: Retry unresolved tickers
        run: |
          python scripts/retry_unresolved_tickers.py data
        working-directory: .

      - name: Upload merged artifact
        uses: actions/upload-artifact@v4
        with:
          name: ticker-info
          path: |
            data/ticker_info.json
            data/unresolved_tickers.txt
            logs/merge_ticker_info.log
          retention-days: 5

      - name: Commit and push final changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git stash push --include-untracked
          git pull --rebase origin main
          git stash pop || echo "No stash to pop"
          git add data/ticker_info.json data/partition_summary.json data/unresolved_tickers.txt logs/*
          edt_time=$(date -u -d "4 hours ago" +"%I:%M %p EDT on %A, %B %d, %Y")
          git commit -m "Commit Phase 1 final outputs: ticker_info.json, unresolved_tickers.txt, partition_summary.json and logs [${edt_time}]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git || echo "Push failed, possibly no changes"

      - name: Print workflow end time (EDT)
        run: |
          echo "Workflow ended at $(date -u -d '4 hours ago' +'%I:%M %p EDT on %A, %B %d, %Y')"

  build-ticker-price:
    needs: merge-ticker-info
    strategy:
      fail-fast: false
      matrix:
        part_index: [0, 1, 2, 3]  # Four partitions for Phase 2
        part_total: [4]
    runs-on: ubuntu-latest
    timeout-minutes: 180  # Allow up to 180 minutes for safety

    steps:
      - name: Print workflow start time (EDT)
        run: |
          echo "Workflow started at $(date -u -d '4 hours ago' +'%I:%M %p EDT on %A, %B %d, %Y')"

      - uses: actions/checkout@v4

      - name: Download ticker info artifact
        uses: actions/download-artifact@v4
        with:
          name: ticker-info
          path: data

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yahooquery pandas requests tqdm

      - name: Run ticker price builder (partition ${{ matrix.part_index }}, Phase 2)
        run: |
          python scripts/build_ticker_price.py \
            --part-index ${{ matrix.part_index }} \
            --part-total ${{ matrix.part_total }} \
            --verbose
        working-directory: .

      - name: Upload price artifact
        uses: actions/upload-artifact@v4
        with:
          name: ticker-price-part-${{ matrix.part_index }}
          path: |
            data/ticker_price_part_${{ matrix.part_index }}.json
            logs/build_ticker_price.log
          retention-days: 5

      - name: Print workflow end time (EDT)
        run: |
          echo "Workflow ended at $(date -u -d '4 hours ago' +'%I:%M %p EDT on %A, %B %d, %Y')"

  merge-ticker-price:
    needs: build-ticker-price
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Print workflow start time (EDT)
        run: |
          echo "Workflow started at $(date -u -d '4 hours ago' +'%I:%M %p EDT on %A, %B %d, %Y')"

      - uses: actions/checkout@v4

      - name: Download price artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: ticker-price-part-*
          merge-multiple: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yahooquery pandas requests tqdm

      - name: Prepare files for merge
        run: |
          mkdir -p data logs
          find artifacts -type f -name "ticker_price_part_*.json" -exec cp {} data/ \; || true
          ls -l data/ | grep -E "ticker_price_part_" || echo "No ticker_price_part_*.json files copied"
        working-directory: .

      - name: Merge ticker price files
        run: |
          python scripts/merge_ticker_price.py data --part-total 4
        working-directory: .

      - name: Upload final price artifact
        uses: actions/upload-artifact@v4
        with:
          name: ticker-price
          path: |
            data/ticker_price.json
            logs/build_ticker_price.log
            logs/merge_ticker_price.log
          retention-days: 5

      - name: Stage and commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git stash push --include-untracked
          git pull --rebase origin main
          git stash pop || echo "No stash to pop"
          git add data/ticker_info.json data/ticker_price.json logs/ data/partition_summary.json data/unresolved_tickers.txt
          edt_time=$(date -u -d "4 hours ago" +"%I:%M %p EDT on %A, %B %d, %Y")
          git commit -m "Update ticker info and price (auto) [${edt_time}]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git || echo "Push failed, possibly no changes"

      - name: Print workflow end time (EDT)
        run: |
          echo "Workflow ended at $(date -u -d '4 hours ago' +'%I:%M %p EDT on %A, %B %d, %Y')"
