name: Build Ticker Info

on:
  workflow_dispatch:
  schedule:
    - cron: "15 5 * * *"  # daily at 05:15 UTC

jobs:
  build-ticker-info:
    strategy:
      fail-fast: false
      matrix:
        part_index: [0, 1]  # Two partitions
        part_total: [2]
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Reduced to 60 minutes

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ticker info builder (partition ${{ matrix.part_index }})
        run: |
          python scripts/build_ticker_info.py \
            --part-index ${{ matrix.part_index }} \
            --part-total ${{ matrix.part_total }} \
            --verbose
        working-directory: .

      - name: Upload partition artifact
        uses: actions/upload-artifact@v4
        with:
          name: ticker-info-part-${{ matrix.part_index }}
          path: |
            data/ticker_info_part_${{ matrix.part_index }}.json
            data/partition_summary.json
            data/unresolved_tickers.txt
            logs/build_ticker_info.log
          retention-days: 5

  merge-ticker-info:
    needs: build-ticker-info
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Download partition artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: ticker-info-part-*
          merge-multiple: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare files for merge
        run: |
          mkdir -p data logs
          find artifacts -type f -name "ticker_info_part_*.json" -exec cp {} artifacts/ \; || true
          find artifacts -type f -name "partition_summary.json" -exec cp {} artifacts/ \; || true
          find artifacts -type f -name "unresolved_tickers.txt" -exec cp {} artifacts/ \; || true
          ls -l artifacts/ | grep -E "ticker_info_part_|partition_summary.json|unresolved_tickers.txt" || echo "No expected files copied"

      - name: Retry unresolved tickers
        run: |
          python scripts/retry_unresolved_tickers.py artifacts
        working-directory: .

      - name: Merge ticker_info.json files
        run: |
          python scripts/merge_ticker_info.py artifacts
        working-directory: .

      - name: Upload merged artifact
        uses: actions/upload-artifact@v4
        with:
          name: ticker-info
          path: |
            data/ticker_info.json
            data/unresolved_tickers.txt
            logs/merge_ticker_info.log
          retention-days: 5

  build-ticker-price:
    needs: merge-ticker-info
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Download ticker info artifact
        uses: actions/download-artifact@v4
        with:
          name: ticker-info
          path: data

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ticker price builder (part 1)
        run: |
          python scripts/build_ticker_price.py \
            --part-index 0 \
            --part-total 2 \
            --verbose
        working-directory: .

      - name: Run ticker price builder (part 2)
        run: |
          python scripts/build_ticker_price.py \
            --part-index 1 \
            --part-total 2 \
            --verbose
        working-directory: .

      - name: Merge ticker price files
        run: |
          python scripts/merge_ticker_price.py
        working-directory: .

      - name: Upload price artifact
        uses: actions/upload-artifact@v4
        with:
          name: ticker-price
          path: |
            data/ticker_price.json
            logs/build_ticker_price.log
          retention-days: 5

      - name: Stage and commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add data/ticker_info.json data/ticker_price.json logs/
          edt_time=$(date -u -d "4 hours ago" +"%I:%M %p EDT on %A, %B %d, %Y")
          git commit -m "Update ticker info and price (auto) [${edt_time}]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git || echo "Push failed, possibly no changes"
