name: Build Ticker Info

on:
  workflow_dispatch:
  schedule:
    - cron: "15 5 * * *"  # daily at 05:15 UTC

jobs:
  build-parts:
    strategy:
      fail-fast: false
      matrix:
        part_index: [0, 1]   # 2 partitions
        part_total: [2]
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run builder (partition ${{ matrix.part_index }})
        run: |
          python scripts/build_ticker_info.py \
            --part-index ${{ matrix.part_index }} \
            --part-total ${{ matrix.part_total }} \
            --verbose

      - name: Upload partition artifact
        uses: actions/upload-artifact@v4
        with:
          name: ticker-info-part-${{ matrix.part_index }}
          path: |
            data/ticker_info.json
            data/partition_summary.json
            data/unresolved_tickers.txt
            logs/build_ticker_info.log
          retention-days: 5

  merge:
    needs: build-parts
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Download partition artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: ticker-info-part-*
          merge-multiple: false

      - name: List downloaded artifacts
        run: |
          echo "Downloaded artifacts:"
          ls -R artifacts

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Merge ticker_info.json files
        run: |
          python scripts/merge_ticker_info.py

      - name: Verify ticker_info.json
        run: |
          python scripts/verify_ticker_info.py
        continue-on-error: true

      - name: Commit & Push (if changed)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -n "$(git status --porcelain data/ticker_info.json)" ]]; then
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add data/ticker_info.json
            git commit -m "Update ticker_info.json (auto) [$(date -u +%Y-%m-%dT%H:%M:%SZ)]"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
            echo "Changes committed and pushed."
          else
            echo "No changes to data/ticker_info.json."
          fi
