name: Build Ticker Info

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ticker-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run build_ticker_info.py (Phase 1)
        run: |
          python scripts/build_ticker_info.py --part-index 0 --part-total 2
          python scripts/build_ticker_info.py --part-index 1 --part-total 2

      - name: Run retry_unresolved_tickers.py
        run: python scripts/retry_unresolved_tickers.py artifacts

      - name: Run merge_ticker_info.py
        run: python scripts/merge_ticker_info.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/ticker_info.json data/ticker_info_part_*.json data/unresolved_tickers.txt logs/*
          git commit -m "Commit Phase 1 outputs: ticker_info.json, partitions, unresolved_tickers.txt, and logs" || echo "No changes to commit"
          git push

  build-ticker-price:
    runs-on: ubuntu-latest
    needs: build-ticker-info
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run build_ticker_price.py (Phase 2)
        run: |
          python scripts/build_ticker_price.py --part-index 0 --part-total 2
          python scripts/build_ticker_price.py --part-index 1 --part-total 2

      - name: Commit and push price data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/ticker_price_part_*.json logs/build_ticker_price.log
          git commit -m "Commit Phase 2 outputs: ticker_price_part_X.json and logs" || echo "No changes to commit"
          git push
