name: 📊 Calculate RS Ratings

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1-5'  # Every weekday at 12:00 UTC

jobs:
  fetch-rs:
    strategy:
      matrix:
        partition: [0, 1, 2, 3]
    runs-on: ubuntu-latest
    name: fetch-rs-${{ matrix.partition }}
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4

      - name: 🔍 Verify ticker_price.json
        run: |
          if [ ! -f data/ticker_price.json ]; then
            echo "Error: data/ticker_price.json not found"
            exit 1
          fi

      - name: 🗕️ Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 🔬 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: 📦 Install dependencies
        run: |
          pip install --upgrade pip
          pip install yahooquery pandas numpy tqdm arcticdb

      - name: 🔢 Verify calculate_rs.py checksum
        run: |
          if [ ! -f scripts/calculate_rs.py ]; then
            echo "Error: scripts/calculate_rs.py not found"
            exit 1
          fi
          echo "SHA256: $(sha256sum scripts/calculate_rs.py)"

      - name: 🔎 Verify calculate_rs.py arguments
        run: |
          python scripts/calculate_rs.py -h

      - name: ▶️ Fetch data for partition ${{ matrix.partition }}
        run: |
          mkdir -p tmp/arctic_db
          mkdir -p logs
          rm -f logs/failed_tickers.log
          python scripts/calculate_rs.py data/ticker_price.json \
            --log-file logs/failed_tickers.log \
            --partition ${{ matrix.partition }} \
            --total-partitions 4

      - name: 📦 Upload ArcticDB data
        uses: actions/upload-artifact@v4
        with:
          name: arctic-db-${{ matrix.partition }}
          path: tmp/arctic_db/

      - name: 📊 Upload failed tickers log
        uses: actions/upload-artifact@v4
        with:
          name: failed-tickers-${{ matrix.partition }}
          path: logs/failed_tickers.log
          if-no-files-found: ignore

  validate-arctic-data:
    needs:
      - fetch-rs
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⬇️ Download ArcticDB partitions
        uses: actions/download-artifact@v4
        with:
          path: tmp
          pattern: arctic-db-*
          
      - name: 🧪 Install ArcticDB
        run: |
          pip install arcticdb

      - name: 🪩 Merge ArcticDB partitions into one DB
        run: |
          echo "🔍 Checking for ArcticDB partition folders..."
          if ls tmp/arctic-db-* 1> /dev/null 2>&1; then
             echo "✅ ArcticDB partitions found:"
             find tmp -type d -name "arctic-db-*"
          else
             echo "❌ No ArcticDB partition folders (tmp/arctic-db-*) found"
             exit 1
          fi

          echo "🧹 Cleaning any previous merged DB at tmp/arctic_db..."
          rm -rf tmp/arctic_db
          mkdir -p tmp/arctic_db

          echo "🚀 Running ArcticDB merge script..."
          python3 scripts/merge_arcticdb.py --source-root tmp --dest-path tmp/arctic_db

          echo "📂 Listing merged DB contents:"
          ls -la tmp/arctic_db

          if [ -z "$(ls -A tmp/arctic_db 2>/dev/null)" ]; then
             echo "❌ Merge failed: tmp/arctic_db is empty"
             exit 1
          else
             echo "✅ ArcticDB merge completed successfully"
          fi

      - name: 🔮 Verify merged ArcticDB (Top 10 symbols)
        run: |
          pip install arcticdb pandas
          python <<EOF
          import arcticdb as adb
          try:
            arctic = adb.Arctic("lmdb://tmp/arctic_db")
            if not arctic.has_library("prices"):
              raise ValueError("Library 'prices' not found.")
            lib = arctic.get_library("prices")
            symbols = lib.list_symbols()
            print(f"✅ Found {len(symbols)} symbols")
            print("🕟 Sample symbols:", symbols[:10])
          except Exception as e:
            print(f"❌ ArcticDB error: {e}")
            exit(1)
          EOF

      - name: 🫼 Remove lock file
        run: |
          find tmp/arctic_db -name "lock.mdb" -exec rm -f {} \;

      - name: 📦 Upload merged ArcticDB
        uses: actions/upload-artifact@v4
        with:
          name: arctic-db-merged
          path: tmp/arctic_db

  calculate-rs:
    needs: validate-arctic-data
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⬇️ Download merged ArcticDB
        uses: actions/download-artifact@v4
        with:
          name: arctic-db-merged
          path: tmp/arctic_db

      - name: 📆 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas numpy tqdm arcticdb

      - name: 🔮 Verify ArcticDB before RS calculation
        run: |
          python <<EOF
          import arcticdb as adb
          try:
            arctic = adb.Arctic("lmdb://tmp/arctic_db")
            if not arctic.has_library("prices"):
                raise ValueError("Library 'prices' not found")
            print("\u2705 ArcticDB loaded successfully")
          except Exception as e:
            print(f"\u274c Failed to load ArcticDB: {e}")
            exit(0)
          EOF

      - name: 📃 Run RS calculation
        run: |
          mkdir -p logs data
          python scripts/calculate_rs_from_db.py \
            --arctic-db-path tmp/arctic_db \
            --reference-ticker SPY \
            --output-dir data \
            --log-file logs/failed_tickers.log \
            --metadata-file data/ticker_price.json
            
      - name: 📃 Archive and Log RS Results
        run: |
          mkdir -p archive RS_Logs
          current_date=$(date -u -d "4 hours ago" +"%m%d%Y")
          cp data/rs_stocks.csv archive/rs_stocks_${current_date}.csv
          cp data/rs_industries.csv archive/rs_industries_${current_date}.csv
          cp data/RSRATING.csv archive/RSRATING_${current_date}.csv
          cp data/rs_stocks.csv RS_Logs/rs_stocks_${current_date}.csv
          cp data/rs_industries.csv RS_Logs/rs_industries_${current_date}.csv
          cp data/RSRATING.csv RS_Logs/RSRATING_${current_date}.csv
          find archive -type f -name "*.csv" -mtime +90 -delete
          find RS_Logs -type f -name "*.csv" -mtime +90 -delete

      - name: 📤 Commit and Push Results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
      
          echo "🔍 Git status before commit:"
          git status
      
          echo "➕ Staging CSV result files..."
          git add archive/*.csv RS_Logs/*.csv
      
          echo "📋 Diff of staged changes:"
          git diff --cached
      
          # Only commit if there are staged changes
          if git diff --cached --quiet; then
            echo "⚠️ No changes to commit."
          else
            commit_date=$(date -u -d '4 hours ago' +'%m%d%Y')
            git commit -m "Add RS results for ${commit_date}"
            git push
            echo "✅ Changes committed and pushed."
          fi

      - name: 🗓️ Upload outputs
        uses: actions/upload-artifact@v4
        with:
          name: rs-results
          path: |
            data/*.csv
            logs/failed_tickers.log
            archive/*.csv
