name: 📊 Calculate RS Ratings

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1-5'  # Every weekday at 12:00 UTC

jobs:
  fetch-rs:
    strategy:
      matrix:
        partition: [0, 1, 2, 3]
    runs-on: ubuntu-latest
    name: fetch-rs-${{ matrix.partition }}
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4

      - name: 🔍 Verify ticker_price.json
        run: |
          if [ ! -f data/ticker_price.json ]; then
            echo "Error: data/ticker_price.json not found"
            exit 1
          fi

      - name: 📅 Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 🔬 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: 📦 Install dependencies
        run: |
          pip install --upgrade pip
          pip install yahooquery pandas numpy tqdm arcticdb

      - name: 🔢 Verify calculate_rs.py checksum
        run: |
          if [ ! -f scripts/calculate_rs.py ]; then
            echo "Error: scripts/calculate_rs.py not found"
            exit 1
          fi
          echo "SHA256: $(sha256sum scripts/calculate_rs.py)"

      - name: 🔎 Verify calculate_rs.py arguments
        run: |
          python scripts/calculate_rs.py -h

      - name: ⏳ Simulate partitioned fetch
        run: echo "Simulating RS fetch for partition ${{ matrix.partition }}"

  validate-arctic-data:
    needs:
      - fetch-rs
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⬇️ Download ArcticDB partitions
        uses: actions/download-artifact@v4
        with:
          path: tmp
          pattern: arctic-db-*

      - name: 🧹 Merge ArcticDB artifacts
        run: |
          rm -rf tmp/arctic_db
          mkdir -p tmp/arctic_db/prices
          for dir in tmp/arctic_db-*; do
            if [ -d "$dir/prices" ]; then
              cp -r "$dir/prices/." tmp/arctic_db/prices/
            fi
          done

      - name: 🧼 Remove lock file
        run: |
          find tmp/arctic_db -name "lock.mdb" -exec rm -f {} \;

      - name: 📦 Upload merged ArcticDB
        uses: actions/upload-artifact@v4
        with:
          name: arctic-db-merged
          path: tmp/arctic_db

  calculate-rs:
    needs: validate-arctic-data
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⬇️ Download merged ArcticDB
        uses: actions/download-artifact@v4
        with:
          name: arctic-db-merged
          path: tmp/arctic_db

      - name: 📆 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas numpy tqdm arcticdb

      - name: 📊 Run RS calculation
        run: |
          mkdir -p logs data
          python scripts/calculate_rs_from_db.py \
            --arctic-db-path lmdb://tmp/arctic_db \
            --min-percentile 85 \
            --reference-ticker SPY \
            --output-dir data \
            --log-file logs/failed_tickers.log \
            --metadata-file data/ticker_price.json

      - name: 📃 Archive rs_stocks.csv
        run: |
          mkdir -p archive
          current_date=$(date -u -d "4 hours ago" +"%m%d%Y")
          cp data/rs_stocks.csv archive/rs_stocks_${current_date}.csv
          find archive -type f -name "rs_stocks_*.csv" -mtime +90 -delete

      - name: 📅 Upload outputs
        uses: actions/upload-artifact@v4
        with:
          name: rs-results
          path: |
            data/*.csv
            logs/failed_tickers.log
            archive/*.csv
