name: Copy rs_stocks.csv to RS Repository

on:
  push:
    branches:
      - main
    paths:
      - RS_Data/rs_stocks.csv

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      # Check out the RS-Rating repository
      - name: Checkout RS-Rating repository
        uses: actions/checkout@v4
        with:
          repository: Vinubhai1961/RS-Rating
          ref: main

      # Set up date variable for archive file naming
      - name: Set up date variable
        id: date
        run: echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

      # Check out the RS repository
      - name: Checkout RS repository
        uses: actions/checkout@v4
        with:
          repository: Vinubhai1961/RS
          ref: main
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      # Copy rs_stocks.csv to Data directory
      - name: Copy rs_stocks.csv to Data
        run: |
          cp RS_Data/rs_stocks.csv Data/rs_stocks.csv

      # Copy rs_stocks.csv to archive with date suffix
      - name: Copy rs_stocks.csv to archive with date
        run: |
          cp RS_Data/rs_stocks.csv archive/rs_stocks_${{ env.DATE }}.csv

      # Commit and push changes to RS repository
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add Data/rs_stocks.csv archive/rs_stocks_${{ env.DATE }}.csv
          git commit -m "Copy rs_stocks.csv to Data and archive (date: ${{ env.DATE }})"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
