name: 📤 Copy Files to Output Repo

on:
  schedule:
    # Run Mon–Fri at 6:00PM EST (23:00 UTC)
    - cron: "0 22 * * 1-5"
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy selected files to output repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Clone destination repo
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/dhruvisha0518/output.git output-repo

          # Ensure the output folder exists
          mkdir -p output-repo/output

          # Copy specific files with new names
          cp RS_Data/RSRATING_TV.csv   output-repo/output/RSRATING.csv
          cp RS_Data/rs_industries.csv output-repo/output/rs_industries.csv

          # Copy all rs_stocks_part*.csv files dynamically
          for f in RS_Data/rs_stocks_part*.csv; do
            cp "$f" output-repo/output/
          done

          cd output-repo
          git add .
          git commit -m "Automated file sync on $(date)" || echo "No changes to commit"
          git push origin main
