name: 📈 Filter Top RS Opportunities

on:
  workflow_dispatch:
  schedule:
    - cron: '30 21 * * 1-5'  # Runs every weekday at 5:30 PM UTC (1:30 PM ET)

jobs:
  filter_top_rs:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: 📦 Install Dependencies
        run: pip install pandas

      - name: 🧮 Run RS Opportunity Filter
        run: python scripts/filter_top_rs.py

      - name: 📤 Commit & Push Results
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          if [ -f "IBD-20/rs_opportunities_07252025.csv" ]; then
            git add IBD-20/rs_opportunities_07252025.csv
            git commit -m "📈 Add RS Opportunities Report for 2025-07-25"
            git push
          else
            echo "⚠️ Report file not found. Nothing to commit."
