# GitHub Actions workflow: NASDAQ Traded Analysis

name: NASDAQ Traded Analysis

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 0'  # Every Sunday at 10 AM UTC

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install matplotlib

      - name: Run NASDAQ Traded Analysis Script
        run: python scripts/NASDAQ.py

      - name: List contents of scripts directory
        run: ls -l scripts/ || echo "scripts directory missing"

      - name: Move generated outputs (ignore if missing)
        run: |
          mv scripts/analysis_output.txt analysis_output.txt 2>/dev/null || true
          mv scripts/nasdaq_analysis.png nasdaq_analysis.png 2>/dev/null || true

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update NASDAQ analysis outputs for $(date +'%Y-%m-%d')" || echo "Nothing to commit"

      - name: Pull latest changes to avoid push conflicts
        run: git pull --rebase origin main

      - name: Push changes to repository
        env:
          PAT: ${{ secrets.PAT }}
        run: git push https://dpatelj88:${{ secrets.PAT }}@github.com/dpatelj88/RS-Rating HEAD:main
