name: Split rs_stocks.csv

# Controls when the workflow runs
on:
  workflow_dispatch: # Manual trigger only

jobs:
  split-csv:
    name: Split rs_stocks.csv into chunks
    runs-on: ubuntu-latest

    steps:
      # Check out the repository to access rs_stocks.csv
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install pandas
        run: pip install pandas

      # Delete existing split files to ensure overwrite
      - name: Delete existing split files
        run: |
          rm -f RS_Data/rs_stocks_part*.csv
          echo "Deleted existing rs_stocks_part*.csv files"

      # Run Python script to split rs_stocks.csv
      - name: Split CSV file
        run: python scripts/split_rs_stocks.py

      # Commit and push the split files
      - name: Commit split files
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add RS_Data/rs_stocks_part*.csv
          git commit -m "Split rs_stocks.csv into 4000-record chunks ($(date))"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
