name: Split rs_stocks.csv

on:
  workflow_dispatch: # Manual trigger
  workflow_run:
    workflows: ["📊 Calculate RS Ratings"]
    types: [completed]
    branches: [main]

jobs:
  split-csv:
    name: Split rs_stocks.csv into chunks
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Print workflow start time (EDT)
        run: |
          echo "Workflow started at $(date -u -d '4 hours ago' +'%I:%M %p EDT on %A, %B %d, %Y')"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pandas
        run: pip install pandas

      # Clean out previous split files and show exactly what was removed
      - name: Delete existing split files
        run: |
          echo "Looking for old rs_stocks_part*.csv files in RS_Data/"
          files=$(find RS_Data -maxdepth 1 -type f -name "rs_stocks_part*.csv" -print)
          if [ -z "$files" ]; then
            echo "No old split files found."
          else
            echo "Deleting the following files:"
            echo "$files" | sed 's/^/ - /'
            # Delete safely even if filenames contain spaces/newlines
            while IFS= read -r f; do
              rm -f -- "$f"
            done <<< "$files"
          fi

      - name: Split CSV file
        run: python scripts/split_rs_stocks.py

      - name: List RS_Data after split
        run: |
          echo "RS_Data now contains:"
          ls -la RS_Data || true

      - name: Commit split files
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          # IMPORTANT: stage the entire directory so deletions are included
          git add -A RS_Data

          echo "Staged changes:"
          git status --porcelain

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Split rs_stocks.csv into 4000-record chunks [$(date -u -d '4 hours ago' +'%I:%M %p EDT on %A, %B %d, %Y')]"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print workflow end time (EDT)
        run: |
          echo "Workflow ended at $(date -u -d '4 hours ago' +'%I:%M %p EDT on %A, %B %d, %Y')"
