name: Stock Momentum Analysis

on:
  workflow_dispatch: # Manual trigger

jobs:
  analyze-stocks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy

      - name: Create IBD-20 folder if it doesn't exist
        run: mkdir -p IBD-20

      - name: Run stock analysis
        run: python scripts/stock_momentum.py

      - name: Commit results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add IBD-20/TopStockOpportunities.csv
          git commit -m "Update IBD-20/TopStockOpportunities.csv with latest momentum analysis"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
