name: Update Stocks Data

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at 12 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-stocks:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Use a stable Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas yfinance tqdm

      # Create data and logs directories if they don't exist
      - name: Create directories
        run: |
          mkdir -p data
          mkdir -p logs

      # Run the update_stocks.py script and capture logs
      - name: Run update_stocks.py
        run: |
          python update_stocks.py > logs/update_stocks_$(date +%Y%m%d_%H%M%S).log 2>&1

      # Commit and push changes to data folder
      - name: Commit output files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/*
          git add logs/*
          git commit -m "Update stock data and logs - $(date +%Y%m%d_%H%M%S)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
