name: Run VCP Stock Scanner

# Controls when the workflow runs
on:
  workflow_dispatch: # Manual trigger only
  push:
    paths:
      - 'archive/**.csv'
      - 'scripts/VCP_Scan.py'
      - '.github/workflows/scan.yml'
      
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install pandas

      - name: Run VCP Scan
        run: |
          python scripts/VCP_Scan.py

      - name: Commit and push output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add IBD-20/vcp_*.csv
          git commit -m "Add filtered stock scan results" || echo "No changes to commit"
          git push
